return {
  -- { "folke/flash.nvim", enabled = false },
  -- -- For completion-----------
  -- { "hrsh7th/nvim-cmp", enabled = true },
  -- {
  --   "L3MON4D3/LuaSnip",
  --   enabled = true,
  -- },
  -- {
  --   "rafamadriz/friendly-snippets",
  --   enabled = true,
  -- },
  -- {
  --   "saadparwaiz1/cmp_luasnip",
  --   enabled = true,
  -- },
  -- --------------------- colorscheme
  -- {
  --   "catppuccin/nvim",
  --   enabled = false,
  -- },
  -- ------------------ better ui
  -- { "rcarriga/nvim-notify", enabled = false },
  -- { "stevearc/dressing.nvim", enabled = false },
  -- { "folke/noice.nvim", enabled = false },
  -- ---------------utils
  -- {
  --   "dstein64/vim-startuptime",
  --   enabled = false,
  -- },
  --
  -- {
  --   "folke/trouble.nvim",
  --   enabled = false,
  -- },
  -- {
  --   "windwp/nvim-ts-autotag",
  --   enabled = false,
  -- },
  -- {
  --   "echasnovski/mini.ai",
  --   enabled = false,
  -- },
  -- { "windwp/nvim-autopairs", enabled = true },
  -- {
  --   "echasnovski/mini.surround",
  --   enabled = false,
  -- },
  -- {
  --   "echasnovski/mini.pairs",
  --   enabled = true,
  -- },
  -- { "ggandor/flit.nvim", enabled = false },
  -- {
  --   "nvim-pack/nvim-spectre",
  --   enabled = false,
  -- },
  --
  -- {
  --   "folke/persistence.nvim",
  --   enabled = false,
  -- },
  -- {
  --   "RRethy/vim-illuminate",
  --   enabled = true,
  -- },
  -- {
  --   "nvimdev/dashboard-nvim",
  --   enabled = false,
  -- },
  -- {
  --   "folke/todo-comments.nvim",
  --   enabled = false,
  -- },
  -- {
  --   "zbirenbaum/copilot.lua",
  --   enabled = false,
  -- },
  -- {
  --   "gbprod/yanky.nvim",
  --   enabled = false,
  -- },
  -- { "echasnovski/mini.nvim", enabled = false },
  -- { "ggandor/leap.nvim", enabled = false },
  -- { "simrat39/symbols-outline.nvim", enabled = false },
}
